name: image-prosody

# Workflow is triggered manually only.
on:
  workflow_dispatch:

env:
  CONTEXT: prosody
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          memory=4g

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Version
      run: |
        VER=$(grep -E -m 1 -v '^#|^\s*$' VERSION 2>/dev/null | xargs)
        echo "VERSION=${VER:-unstable-$(date +'%Y%m%d')}" >> $GITHUB_ENV

    - name: Extract Short Tag
      id: extract_tag
      run: |
        if [[ "${{ env.VERSION }}" == stable-* ]]; then
          echo "short=stable" >> $GITHUB_OUTPUT
        elif [[ "${{ env.VERSION }}" == unstable-* ]]; then
          echo "short=unstable" >> $GITHUB_OUTPUT
        else
          echo "short=" >> $GITHUB_OUTPUT
        fi

    - name: Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.CONTEXT }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ env.VERSION }}
          ${{
            steps.extract_tag.outputs.short != '' &&
            format('type=raw,value={0}', steps.extract_tag.outputs.short) ||
            ''
          }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ env.CONTEXT }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
