name: image-base

on:
  workflow_dispatch:

env:
  CONTEXT: base
  IMAGE_VERSION: unstable-20251226
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Short Tag
      id: extract_tag
      run: |
        if [[ "${{ env.IMAGE_VERSION }}" == stable-* ]]; then
          echo "short=stable" >> $GITHUB_OUTPUT
        elif [[ "${{ env.IMAGE_VERSION }}" == unstable-* ]]; then
          echo "short=unstable" >> $GITHUB_OUTPUT
        else
          echo "short=" >> $GITHUB_OUTPUT
        fi

    - name: Metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.CONTEXT }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ env.IMAGE_VERSION }}
          ${{
            steps.extract_tag.outputs.short != '' &&
            format('type=raw,value={0}', steps.extract_tag.outputs.short) ||
            ''
          }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./${{ env.CONTEXT }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
